name: Ultralytics Actions
on:
  push:
    branches:
      - main

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Run Ultralytics Actions
        uses: ultralytics/actions@main
        with:
          brave_api_key: ${{ secrets.BRAVE_API_KEY }}
          first_issue_response: "\U0001F44B Hello @${{ github.actor }}, thank you\
            \ for your interest in YOLOv5 \U0001F680! Please visit our \u2B50\uFE0F\
            \ [Tutorials](https://docs.ultralytics.com/yolov5/) to get started, where\
            \ you can find quickstart guides for simple tasks like [Custom Data Training](https://docs.ultralytics.com/yolov5/tutorials/train_custom_data/)\
            \ all the way to advanced concepts like [Hyperparameter Evolution](https://docs.ultralytics.com/yolov5/tutorials/hyperparameter_evolution/).\n\
            If this is a \U0001F41B Bug Report, please provide a **minimum reproducible\
            \ example** to help us debug it.\nIf this is a custom training \u2753\
            \ Question, please provide as much information as possible, including\
            \ dataset image examples and training logs, and verify you are following\
            \ our [Tips for Best Training Results](https://docs.ultralytics.com/guides/model-training-tips/).\n\
            ## Requirements\n[**Python>=3.8.0**](https://www.python.org/) with all\
            \ [requirements.txt](https://github.com/ultralytics/yolov5/blob/master/requirements.txt)\
            \ installed including [**PyTorch>=1.8**](https://pytorch.org/get-started/locally/).\
            \ To get started:\n```bash\ngit clone https://github.com/ultralytics/yolov5\
            \  # clone\ncd yolov5\npip install -r requirements.txt  # install\n```\n\
            ## Environments\nYOLOv5 may be run in any of the following up-to-date\
            \ verified environments (with all dependencies including [CUDA](https://developer.nvidia.com/cuda)/[CUDNN](https://developer.nvidia.com/cudnn),\
            \ [Python](https://www.python.org/) and [PyTorch](https://pytorch.org/)\
            \ preinstalled):\n- **Notebooks** with free GPU: <a href=\"https://bit.ly/yolov5-paperspace-notebook\"\
            ><img src=\"https://assets.paperspace.io/img/gradient-badge.svg\" alt=\"\
            Run on Gradient\"></a> <a href=\"https://colab.research.google.com/github/ultralytics/yolov5/blob/master/tutorial.ipynb\"\
            ><img src=\"https://colab.research.google.com/assets/colab-badge.svg\"\
            \ alt=\"Open In Colab\"></a> <a href=\"https://www.kaggle.com/models/ultralytics/yolov5\"\
            ><img src=\"https://kaggle.com/static/images/open-in-kaggle.svg\" alt=\"\
            Open In Kaggle\"></a>\n- **Google Cloud** Deep Learning VM. See [GCP Quickstart\
            \ Guide](https://docs.ultralytics.com/yolov5/environments/google_cloud_quickstart_tutorial/)\n\
            - **Amazon** Deep Learning AMI. See [AWS Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/aws_quickstart_tutorial/)\n\
            - **Docker Image**. See [Docker Quickstart Guide](https://docs.ultralytics.com/yolov5/environments/docker_image_quickstart_tutorial/)\
            \ <a href=\"https://hub.docker.com/r/ultralytics/yolov5\"><img src=\"\
            https://img.shields.io/docker/pulls/ultralytics/yolov5?logo=docker\" alt=\"\
            Docker Pulls\"></a>\n## Status\n<a href=\"https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml\"\
            ><img src=\"https://github.com/ultralytics/yolov5/actions/workflows/ci-testing.yml/badge.svg\"\
            \ alt=\"YOLOv5 CI\"></a>\nIf this badge is green, all [YOLOv5 GitHub Actions](https://github.com/ultralytics/yolov5/actions)\
            \ Continuous Integration (CI) tests are currently passing. CI tests verify\
            \ correct operation of YOLOv5 [training](https://github.com/ultralytics/yolov5/blob/master/train.py),\
            \ [validation](https://github.com/ultralytics/yolov5/blob/master/val.py),\
            \ [inference](https://github.com/ultralytics/yolov5/blob/master/detect.py),\
            \ [export](https://github.com/ultralytics/yolov5/blob/master/export.py)\
            \ and [benchmarks](https://github.com/ultralytics/yolov5/blob/master/benchmarks.py)\
            \ on macOS, Windows, and Ubuntu every 24 hours and on every commit.\n"
          labels: true
          links: false
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          prettier: true
          python: true
          spelling: true
          summary: true
          token: ${{ secrets._GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
permissions:
  contents: write
  issues: write
  pull-requests: write
