name: Merge main into PRs
on:
  push:
    branches:
      - main

jobs:
  Merge:
    if: github.repository == 'ultralytics/yolov5'
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.x
      - name: Install requirements
        run: 'pip install pygithub

          '
      - id: measurement-4
        name: Record Measurement After Install requirements
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install requirements
          task: get-measurement
      - env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets._GITHUB_TOKEN }}
        name: Merge default branch into PRs
        run: "from github import Github\nimport os\n\ng = Github(os.getenv('GITHUB_TOKEN'))\n\
          repo = g.get_repo(os.getenv('GITHUB_REPOSITORY'))\n\n# Fetch the default\
          \ branch name\ndefault_branch_name = repo.default_branch\ndefault_branch\
          \ = repo.get_branch(default_branch_name)\n\nfor pr in repo.get_pulls(state='open',\
          \ sort='created'):\n    try:\n        # Get full names for repositories\
          \ and branches\n        base_repo_name = repo.full_name\n        head_repo_name\
          \ = pr.head.repo.full_name\n        base_branch_name = pr.base.ref\n   \
          \     head_branch_name = pr.head.ref\n\n        # Check if PR is behind\
          \ the default branch\n        comparison = repo.compare(default_branch.commit.sha,\
          \ pr.head.sha)\n        \n        if comparison.behind_by > 0:\n       \
          \     print(f\"\u26A0\uFE0F PR #{pr.number} ({head_repo_name}:{head_branch_name}\
          \ -> {base_repo_name}:{base_branch_name}) is behind {default_branch_name}\
          \ by {comparison.behind_by} commit(s).\")\n            \n            # Attempt\
          \ to update the branch\n            try:\n                success = pr.update_branch()\n\
          \                assert success, \"Branch update failed\"\n            \
          \    print(f\"\u2705 Successfully merged '{default_branch_name}' into PR\
          \ #{pr.number} ({head_repo_name}:{head_branch_name} -> {base_repo_name}:{base_branch_name}).\"\
          )\n            except Exception as update_error:\n                print(f\"\
          \u274C Could not update PR #{pr.number} ({head_repo_name}:{head_branch_name}\
          \ -> {base_repo_name}:{base_branch_name}): {update_error}\")\n         \
          \       print(\"   This might be due to branch protection rules or insufficient\
          \ permissions.\")\n        else:\n            print(f\"\u2705 PR #{pr.number}\
          \ ({head_repo_name}:{head_branch_name} -> {base_repo_name}:{base_branch_name})\
          \ is up to date with {default_branch_name}.\")\n    except Exception as\
          \ e:\n        print(f\"\u274C Could not process PR #{pr.number}: {e}\")\n"
        shell: python
      - id: measurement-6
        name: Record Measurement After Merge default branch into PRs
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Merge default branch into PRs
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
